### ISSUE TITLE
In `withAuthRequired`, errors thrown in `getServerSideProps` should not redirect

### ISSUE THREAD

**Issue by jclem** [supabase-community/supabase-auth-helpers#71] opened 2022-04-15 19:03 UTC
If an error is thrown in `getServerSideProps`, we don't know that this is an authentication error. Currently, `withAuthRequired` [swallows these errors](https://github.com/supabase-community/supabase-auth-helpers/blob/7a275700b0db392c43b3e381ec801cc779a4dd54/src/nextjs/utils/withAuthRequired.ts#L170-L177) and instead redirects to the `redirectTo` path.

This is a particularly tricky API as implemented today, because even developer mistakes in the implementation of a `getServerSideProps` function will appear as if the redirect happened due to no user being logged in.

**Comment by thorwebdev** [comment] 2022-04-20 04:12
Duplicate of https://github.com/supabase-community/supabase-auth-helpers/issues/46

**Closed by thorwebdev** 2022-04-20 04:12 UTC
